### ISSUE TITLE
Can't run with networkx 1.9

### ISSUE THREAD

**Issue by kaupov** [yuzhichang/cppdep#2]
An error message is thrown

```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
analyzing dependencies among all components ...
Traceback (most recent call last):
  File "C:/Users/kaupov/Documents/PycharmProjects/cppdep/cppdep.py", line 675, in <module>
    main()
  File "C:/Users/kaupov/Documents/PycharmProjects/cppdep/cppdep.py", line 643, in main
    calculate_graph(digraph)
  File "C:/Users/kaupov/Documents/PycharmProjects/cppdep/cppdep.py", line 570, in calculate_graph
    (cycles, dict_node2cycle) = make_DAG(digraph, key_node)
  File "C:\Users\kaupov\Documents\PycharmProjects\cppdep\networkx_ext.py", line 79, in make_DAG
    for ind in range(len(subgraphs)-1, -1, -1):
TypeError: object of type 'generator' has no len()
```

I'm unable to install networkx 1.7 and it's dependencies.

**Comment by yuzhichang** [comment]
This is an API change of networkx. The networkx API changes from version to version. Maybe the better way to manage dependency is packing all into a Docker image.

By the way, the latest master fixed this issue.
